import type { Metadata, NextPage } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWalletProvider } from "@/context/AppWalletProvider";
import { UmiProvider } from "@/context/UmiProvider";

import { AppBar } from "@/components/AppBar";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/utils/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <AppWalletProvider>
            <UmiProvider>
              <AppBar />
              {children}
            </UmiProvider>
          </AppWalletProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
