import type { Metadata, NextPage } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWalletProvider } from "@/context/AppWalletProvider";
import { UmiProvider } from "@/context/UmiProvider";

import { AppBar } from "@/components/AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWalletProvider>
          <UmiProvider>
            <AppBar />
            {children}
          </UmiProvider>
        </AppWalletProvider>
      </body>
    </html>
  );
}
