import type { Metadata, NextPage } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Wallet } from "@/context/Wallet";
import { AppBar } from "@/components/layouts/AppBar";
import { BottomBar } from "@/components/layouts/BottomBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wallet>
          <AppBar />
          {children}
          {/* <BottomBar /> */}
        </Wallet>
      </body>
    </html>
  );
}
